name: Submit agama-openapi to OBS

permissions:
  contents: read

on:
  push:
    branches:
      - main
    # Submit only when stable schema changes
    paths:
      - '[0-9]*/**'

  workflow_dispatch:

env:
  package_name: agama-openapi
  service_file: package/_service

jobs:
  update_obs_package:
    # Do not run in forks
    if: ${{ !github.event.repository.fork }}

    runs-on: ubuntu-latest

    container:
      image: registry.opensuse.org/opensuse/tumbleweed:latest

    steps:
      - name: Configure and refresh repositories
        run: zypper modifyrepo -d repo-non-oss repo-openh264 repo-update && zypper ref

      - name: Install tools
        run: zypper --non-interactive install --no-recommends
             git
             cpio
             obs-service-download_files
             obs-service-format_spec_file
             obs-service-obs_scm
             obs-service-set_version
             obs-service-tar
             osc

      - name: Git Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure osc
        run: .github/workflows/configure_osc.sh
        env:
          OBS_USER: ${{ vars.OBS_USER }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}

      - name: Checkout package from OBS
        run: osc co ${{ vars.OBS_PROJECT }} ${{ env.package_name }}

      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run services
        run: |
          osc service manualrun
          rm -vf *.tgz
        working-directory: ./${{ vars.OBS_PROJECT }}/${{ env.package_name }}

      - name: Check status
        run: osc addremove && osc diff && osc status
        working-directory: ./${{ vars.OBS_PROJECT }}/${{ env.package_name }}

      - name: Commit package to OBS
        run: |
          VERSION="$(sed -e '/^version:/!d' -e 's/version: *\(.*\)/\1/' agama-openapi.obsinfo)"
          COMMIT="$(sed  -e '/^commit:/!d'  -e 's/commit: *\(.*\)/\1/'  agama-openapi.obsinfo)"
          osc commit -m "Updated to ${VERSION} (${COMMIT})"
        working-directory: ./${{ vars.OBS_PROJECT }}/${{ env.package_name }}
