name: Update Website Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'nightly/**'
      - '[0-9]*/**'
      - '.github/workflows/update-website.yml'

  workflow_dispatch:

jobs:
  sync-to-website:
    # Do not run in forks
    if: ${{ !github.event.repository.fork }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenAPI sources
        uses: actions/checkout@v7
        with:
          path: agama-openapi

      - name: Checkout Website sources
        uses: actions/checkout@v7
        with:
          path: website
          repository: ${{ github.repository_owner }}/agama-project.github.io
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git user and email
        run: |
          git config --global user.name "YaST Bot"
          git config --global user.email "yast-devel@opensuse.org"

      - name: Sync OpenAPI specifications to website
        run: |
          mkdir -p website/static/openapi

          # Sync nightly specifications and standalone schemas
          if [ -d "agama-openapi/nightly" ]; then
            rm -rfv website/static/openapi/nightly
            mkdir -p website/static/openapi/nightly
            cp -a agama-openapi/nightly/* website/static/openapi/nightly/
          fi

          # Here it expects that old schema never disappear. If so, then it needs manual removal.
          # Sync versioned release specifications (e.g., 16.1)
          for dir in agama-openapi/[0-9]*; do
            if [ -d "$dir" ]; then
              version=$(basename "$dir")
              mkdir -p "website/static/openapi/$version"
              cp -a "$dir"/* "website/static/openapi/$version/"
            fi
          done

      - name: Check for changes in website repository
        id: check_changes
        run: |
          if [ -n "$(git -C website status --porcelain static/openapi)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes in OpenAPI specifications."
          fi

      - name: Commit and push changes to website
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd website
          git add static/openapi
          git commit -m "Update OpenAPI specifications from agama-openapi"$'\n\n'"agama-openapi commit: ${{ github.sha }}"
          git push origin HEAD:main
